### ISSUE TITLE
Auto seed DB

### ISSUE THREAD

**Issue by richardkeep** [Muetze42/laravel-nova-demo-app#31]
I _accidentally_  😂 deleted all the users.

You can create a cron job [that seeds the DB](https://github.com/Muetze42/laravel-nova-demo-app/blob/main/app/Http/Middleware/AutoLoginMiddleware.php#L30) periodically, like after every 10 minutes.

Thanks for the package though

**Comment by Muetze42** [comment]
Hmm. 
Normally you should not be able to delete anything. Thanks for the tip.

**Comment by Muetze42** [comment]
"Fixed"

https://github.com/Muetze42/laravel-nova-demo-app/commit/dc9bb8f123ec11b6469ec1073eb33a83db07118e
